name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tca
          clean: true

      - name: success
        uses: ./tca
        with:
          tis-password: ${{ secrets.TIS_PASS }}
          mesh-config: ./tca/test/manifest.yaml
          local-only: true

  failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tca
          clean: true

      - name: failure
        id: failure
        uses: ./tca
        continue-on-error: true # Continue even if the job fails
        with:
          tis-password: ${{ secrets.TIS_PASS }}
          mesh-config: |-
            ./tca/test/manifest.yaml
            ./tca/test/failed.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          local-only: true

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: failure
          mode: upsert
          file-path: ${{ steps.failure.outputs.result-file }}

  hybrid-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tca
          clean: true

      - name: hybrid
        id: hybrid
        uses: ./tca
        continue-on-error: true # Continue even if the job fails
        with:
          tis-password: ${{ secrets.TIS_PASS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: hybrid-failure
          mode: upsert
          file-path: ${{ steps.hybrid.outputs.result-file }}
