name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tca
          clean: true

      - name: success
        uses: ./tca
        with:
          tis-password: ${{ secrets.TIS_PASS }}
          mesh-config: ./tca/test/manifest.yaml
          local-only: true

      - name: failure
        uses: ./tca
        continue-on-error: true # Continue even if the job fails
        with:
          tis-password: ${{ secrets.TIS_PASS }}
          mesh-config: |-
            ./tca/test/manifest.yaml
            ./tca/test/failed.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          local-only: true
